### ISSUE TITLE
[Frontend]: Need to make the website Responsive

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch.website.frontend#10]
**Task Description**
You need to make all the components responsive, for the best views on all the devices.

Use the general @media method to implement this feature.

- [x] CSS Code
- [x] Test all the Responsive Methods

**Comment by yashsehgal** [comment]
This issue will be managed by @atharvagadkari05 and other developers.

@atharvagadkari05 Assign this issue to the developers/other contributors.

**Comment by rajesh6161** [comment]
I want to work on this issue as well @yashsehgal  ✔

**Comment by yashsehgal** [comment]
You can get started with this, Although, This has been assigned locally to 2 other contributors already. But let's give it a shot. Go on!
@rajesh6161

**Comment by kal003** [comment]
Hi! This is Kunal. I would like to work on this issue.
