### ISSUE TITLE
[Frontend]: We need a Footer Component for the Website

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch.website.frontend#7]
**This is a new feature request.**

We need a footer component for our website. And Here's the wireframe for that.
![image](https://user-images.githubusercontent.com/62352288/111581576-7f695b80-87df-11eb-9f28-9c5ee63446ce.png)

The above image is the wireframe for the footer, we need to finalize the main UI for this and implement this too. 
We will be using JS-DOM elements to implement this feature.

**These are the milestones**
- [x] Wireframe
- [x] UI/UX Design
- [x] JS-DOM Implementation

Those who are open to work on this issue can comment below for assignment requests. We will love to see your code 😃

**Comment by rajesh6161** [comment]
I want to work on this issue @yashsehgal and will make footer responsive also.

**Comment by yashsehgal** [comment]
> I want to work on this issue @yashsehgal and will make the footer responsive also.

Yes @rajesh6161 you can get started with the issue. Once the UI Design for the footer will be done, You can start with the implementation. 

Also, Join The DesignSystems' Discord Server: https://bit.ly/TDesignSystemsDiscord 

See you there 👍🏽

**Comment by rajesh6161** [comment]
![tds](https://user-images.githubusercontent.com/40054161/111664573-edda0800-8837-11eb-9b1b-40a6e6e569a1.jpg)
Check this design @yashsehgal

**Comment by rajesh6161** [comment]
![Screenshot 2021-03-19 104631](https://user-images.githubusercontent.com/40054161/111735060-5a3d2180-88a1-11eb-8f65-cf369ed240df.jpg)

**Comment by yashsehgal** [comment]
That's great @rajesh6161, Just wait for the responsive design. After implementing that, you can make a PR.
👍🏽
